### ISSUE TITLE
create() method posts to wrong endpoint

### ISSUE THREAD

**Issue by imthepitts** [y-ken/twilio-twimlbin#2]
Creating a new Twimlbin with this gem posts to a non-existent "/save_data" endpoint, which causes a 404. The Twimlbin fails to update with the Twiml in the generated Twimlbin.

**Comment by y-ken** [comment]
Hi @imthepitts 

Thank you for your report!
I've update the endpoint and release gem as v0.0.5 now.
https://rubygems.org/gems/twilio-twimlbin

**Comment by imthepitts** [comment]
Thanks so much for the quick fix!
